package id.ac.itats.skripsi.arga.orm.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TB_EDGE.
 */
public class tb_edge {

    private Long id;
    private String id_edge;
    private String from_node;
    private String to_node;
    private String jarak;

    public tb_edge() {
    }

    public tb_edge(Long id) {
        this.id = id;
    }

    public tb_edge(Long id, String id_edge, String from_node, String to_node, String jarak) {
        this.id = id;
        this.id_edge = id_edge;
        this.from_node = from_node;
        this.to_node = to_node;
        this.jarak = jarak;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_edge() {
        return id_edge;
    }

    public void setId_edge(String id_edge) {
        this.id_edge = id_edge;
    }

    public String getFrom_node() {
        return from_node;
    }

    public void setFrom_node(String from_node) {
        this.from_node = from_node;
    }

    public String getTo_node() {
        return to_node;
    }

    public void setTo_node(String to_node) {
        this.to_node = to_node;
    }

    public String getJarak() {
        return jarak;
    }

    public void setJarak(String jarak) {
        this.jarak = jarak;
    }

}
