package id.ac.itats.skripsi.arga.orm.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TB_NODE.
 */
public class tb_node {

    private Long id;
    private String id_node;
    private String lon_node;
    private String lat_node;

    public tb_node() {
    }

    public tb_node(Long id) {
        this.id = id;
    }

    public tb_node(Long id, String id_node, String lon_node, String lat_node) {
        this.id = id;
        this.id_node = id_node;
        this.lon_node = lon_node;
        this.lat_node = lat_node;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getId_node() {
        return id_node;
    }

    public void setId_node(String id_node) {
        this.id_node = id_node;
    }

    public String getLon_node() {
        return lon_node;
    }

    public void setLon_node(String lon_node) {
        this.lon_node = lon_node;
    }

    public String getLat_node() {
        return lat_node;
    }

    public void setLat_node(String lat_node) {
        this.lat_node = lat_node;
    }

}
